healthcheck:
  interval: 15
  max_concurrent_requests: 100
session:
  request_timeout: 0.5
rate_limiter:
  per_second: 5
  per_host: true
  limit_statuses: [429]
request_retry:
  status: 3
  status_forcelist: [429]
  respect_retry_after_header: true
  backoff_factor: 0.5
  backoff_jitter: 1.0
  connect: 0
  read: 0
  other: 0
logging:
  loggers:
    root:
      level: info
      handlers: [console]
  formatters:
    custom:
      (): healthcheck.helpers.LogFormatter
      base_formatter_args:
        { fmt: "%(asctime)s %(levelname)s %(name)s %(threadName)s %(message)s" }
      info_formatter_args: { fmt: "%(message)s" }
  handlers:
    console:
      class: logging.StreamHandler
      formatter: custom
      stream: ext://sys.stdout
  version: 1
  disable_existing_loggers: false
